version: '3'
services:
  app:
    build: .
    restart: on-failure
    ports: 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/node_modules
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: example
      DATABASE_URL: postgres
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
